### ISSUE TITLE
Secret key seeing impossible and stall my platform/windows

### ISSUE THREAD

**Issue by MrGoesToWar** [stellarchat/desktop-client#164]
After installing several time stellarwallet desktop tryin 32&64bit, I try to see my secret key before continuing but the platform just stall and I can't do anything but only close the program. When I restart it, I can open my wallet but still stalling when I go to my profil and retry to see my secret before saving it.
Can someone help me with this?
Thanks all!

**Comment by copa017** [comment]
For me the same - the app crashes /hangs whenever I press the "Show secret key" button.
No matter if I just created a wallett or I have reopened one.

Win10 / 64bit, Ver. 1709, German

**Comment by Nacirema** [comment]
Same for me. I am using Windows 8.1, 64 bit. Downloaded "StellarDesktopWin64-v3.3.zip". Created "StellarDesktopWin64-v3.3" folder in the Program Files folder and put the unzipped contents in there.. Created a shortcut to "StellarWallet.exe" on my Desktop. Launched the program. Clicked "Create New Account", clicked "Create an empty account.", and saved the wallet file. Entered password twice and clicked "Encrypt account". The "Important:" screen shows that there is a password, and it shows the address, and it shows that there is a secret key. I click "Show secret key" and the whole application window goes black and then an empty rectangular box appears and the cursor is an hourglass cursor. I wait over a minute and nothing changes. I click the "X" closer for the window and Windows says "StellarWallet.exe is not responding". I click "Close the program". I restart the program. Click "select account file" and I select the wallet file, enter the password, and click "Open account". In the menu section at the top I click the address. Since I am not depositing any Lumens to the account unless I know the secret key, I click "Show secret key'. The application window goes black. A moment later a white empty rectangle appears in the middle. The cursor is an hourglass cursor. I click on the window. Windows tells me that "StellarWallet.exe is not responding."  I click "Wait for the program to respond." Still no key, and so I click again and get the warning from Windows that the program is not responding and I click "Close the program."

**Comment by naifamoodi** [comment]
I am having the exact same problem! Any updates on this by the devs?

**Comment by liangran** [comment]
v3.5 upgrade to nwjs 0.28.1，I suggest you to try this version. @MrGoesToWar @copa017 @naifamoodi

**Comment by naifamoodi** [comment]
I just tested this and confirm this is fixed in the latest release i.e. v3.5
